name: Push
on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: todolist-extension/package-lock.json
      - run: npm ci
        working-directory: todolist-extension
      - run: npm test
        working-directory: todolist-extension
  build:
    name: Build ${{ matrix.build_target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_target:
          - chromium
          - firefox
          - web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: todolist-extension/package-lock.json
      - run: npm ci
        working-directory: todolist-extension
      - run: npm run build:${{ matrix.build_target }}
        working-directory: todolist-extension
        env:
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
          UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: todolist-extension-${{ matrix.build_target }}
          path: todolist-extension/dist/${{ matrix.build_target }}
